### ISSUE TITLE
运行报错，怎么解决，谢谢！

### ISSUE THREAD

**Issue by angleboy8** [suqingdong/nsfc#13]
![image](https://user-images.githubusercontent.com/20549943/149160472-15494d9d-0b0f-47ce-98e9-d0c046d2c300.png)
安装成功之后，一运行‘nsfc --version’就报错，如上图。望指教！

**Comment by suqingdong** [comment]
请更新nsfc到最新版 2.0.4
`pip3 install -U nsfc==2.0.4`

同时更新click到最新版本
`pip3 install -U click`

**Comment by angleboy8** [comment]
> 请更新nsfc到最新版 2.0.4 `pip3 install -U nsfc==2.0.4`
> 
> 同时更新click到最新版本 `pip3 install -U click`

非常感谢，问题解决了！
